baseURL = "https://d3efwhw5kd1q0b.cloudfront.net/"
languageCode = "en-us"
theme = "hyde"
title = "Mark Dickinson"
uglyurls = true
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
description = "A Programing Blog"
paginatedsections = ["posts"]
